<?php

declare(strict_types=1);

namespace app\tests\Support;

use app\tests\Support\Helper\Auth;

/** Codeception actor for the api suite; module actions are generated by `codecept build`. */
class ApiTester extends \Codeception\Actor
{
    use _generated\ApiTesterActions;

    /** Send the bearer token of a demo account with the next requests. */
    public function amBearerOf(string $email): void
    {
        $this->haveHttpHeader('Authorization', 'Bearer ' . Auth::token($email));
    }

    /** Assert the error envelope {"error": {"code": ...}} with the given HTTP status. */
    public function seeApiError(int $status, string $code): void
    {
        $this->seeResponseCodeIs($status);
        $this->seeResponseIsJson();
        $this->seeResponseContainsJson(['error' => ['code' => $code]]);
    }
}
