<?php

declare(strict_types=1);

namespace app\tests\Support;

/** Codeception actor for the unit suite; module actions are generated by `codecept build`. */
class UnitTester extends \Codeception\Actor
{
    use _generated\UnitTesterActions;
}
