<?php

use yii\db\Migration;

/**
 * Sensor readings, partitioned by month on recorded_at (brief rule 10); data/schema/sensor_reading.yaml.
 *
 * PostgreSQL requires the partition key in the primary key, so the key is (id, recorded_at) and
 * nothing can hold a foreign key to a reading (alerts reference readings loosely by entity_id).
 * Monthly partitions exist for 2026-01 .. 2027-12; anything else lands in the DEFAULT partition,
 * and `yii partition/ensure` adds months ahead of time.
 */
class m260928_000007_create_sensor_reading extends Migration
{
    public function safeUp()
    {
        $this->execute(<<<'SQL'
            CREATE TABLE sensor_reading (
              id bigint GENERATED BY DEFAULT AS IDENTITY,
              mine_id integer NOT NULL REFERENCES mine (id) ON DELETE RESTRICT ON UPDATE CASCADE,
              sensor_type varchar(24) NOT NULL,
              value numeric(12,4) NOT NULL,
              unit varchar(24) NOT NULL,
              recorded_at timestamptz NOT NULL,
              breached boolean NULL,
              resolved boolean NOT NULL DEFAULT false,
              resolved_at timestamptz NULL,
              PRIMARY KEY (id, recorded_at),
              CONSTRAINT sensor_reading_type_check
                CHECK (sensor_type IN ('ch4', 'ch4_return_air', 'co', 'dust', 'temperature', 'humidity')),
              CONSTRAINT sensor_reading_resolved_check CHECK (resolved = (resolved_at IS NOT NULL))
            ) PARTITION BY RANGE (recorded_at)
            SQL);
        $this->execute('CREATE TABLE sensor_reading_default PARTITION OF sensor_reading DEFAULT');
        $month = new DateTimeImmutable('2026-01-01');
        while ($month < new DateTimeImmutable('2028-01-01')) {
            $next = $month->modify('+1 month');
            $this->execute(sprintf("CREATE TABLE sensor_reading_%s PARTITION OF sensor_reading FOR VALUES FROM ('%s') TO ('%s')",
                $month->format('Y_m'), $month->format('Y-m-d'), $next->format('Y-m-d')));
            $month = $next;
        }
        $this->execute('CREATE INDEX idx_sensor_reading_mine_time ON sensor_reading (mine_id, recorded_at)');
        $this->execute('CREATE INDEX idx_sensor_reading_mine_type_time ON sensor_reading (mine_id, sensor_type, recorded_at DESC)');
        $this->execute('CREATE INDEX idx_sensor_reading_breach ON sensor_reading (mine_id, recorded_at) WHERE breached AND NOT resolved');
    }

    public function safeDown()
    {
        $this->execute('DROP TABLE sensor_reading CASCADE');
    }
}
