"""Login background: AVIF, WebP and JPEG versions of src/assets/login-bg.jpg, and the module that
lists them (src/assets/login-bg/sources.js, read by components/common/BrandBackground.jsx).

    python frontend/scripts/make_login_bg.py

Widths up to the source's own width only (anything wider would just be upscaled - the browser
scales the largest one to cover the window). No metadata is kept. Each file must stay under 300 KB.
"""
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "assets" / "login-bg.jpg"
OUT = ROOT / "src" / "assets" / "login-bg"
WIDTHS = [400, 640, 960, 1440]   # capped at the source width
TRIM = 0                         # px trimmed on every side (e.g. a screenshot's rounded corner)
LIMIT = 300_000                  # bytes per file

OUT.mkdir(parents=True, exist_ok=True)
im = Image.open(SRC).convert("RGB")
if TRIM:
    im = im.crop((TRIM, TRIM, im.width - TRIM, im.height - TRIM))
widths = sorted({min(w, im.width) for w in WIDTHS})
made = {"avif": [], "webp": [], "jpg": []}
for w in widths:
    h = round(im.height * w / im.width)
    frame = im.resize((w, h), Image.LANCZOS) if w != im.width else im
    for ext, opts in (("avif", {"quality": 55, "speed": 4}), ("webp", {"quality": 78, "method": 6}),
                      ("jpg", {"quality": 82, "optimize": True, "progressive": True})):
        path = OUT / f"login-bg-{w}.{ext}"
        # Lower the quality step by step until the file fits.
        while True:
            frame.save(path, format={"jpg": "JPEG"}.get(ext, ext.upper()), **opts)
            size = path.stat().st_size
            if size < LIMIT or opts["quality"] <= 50:
                break
            opts = {**opts, "quality": opts["quality"] - 4}
        assert size < LIMIT, f"{path.name}: {size} bytes"
        made[ext].append(w)
        print(f"{path.name}: {w}x{h}, {size // 1024} KB")

lines = ["// Generated by frontend/scripts/make_login_bg.py - do not edit.", ""]
for ext in made:
    for w in made[ext]:
        lines.append(f'import {ext}{w} from "./login-bg-{w}.{ext}";')
lines.append("")
for ext, name in (("avif", "avif"), ("webp", "webp"), ("jpg", "jpeg")):
    entries = ", ".join(f"`${{{ext}{w}}} {w}w`" for w in made[ext])
    lines.append(f"export const {name} = [{entries}].join(\", \");")
largest = made["jpg"][-1]
lines.append(f"export const fallback = jpg{largest};")
(OUT / "sources.js").write_text("\n".join(lines) + "\n", encoding="utf8")
print("sources.js written")
