<#
Serve the Yii2 API through XAMPP's Apache (mod_php, thread-safe build) on 127.0.0.1:8080.

  scripts\api_server.bat start | stop | restart | status | config

`config` writes a self-contained Apache configuration to api\runtime\apache\ - one virtual host
for api\web, only the modules the API needs, its own pid and error log - and a php.ini that is
XAMPP's own plus OPcache and a larger realpath cache. XAMPP's httpd.conf and php.ini are never
modified, so the XAMPP control panel and any other site keep working as before. `start` always
rewrites the configuration first, so moving the repository needs no manual step.

Apache runs as a normal user process with a hidden console (like scripts\db.bat), and `stop`
ends it. The PHP built-in server (api\serve.bat) remains the fallback.

Override the locations with XAMPP_HOME and API_PORT.
#>
param([string]$Action = "status")
# Note: PowerShell variable names are case-insensitive ($Conf is $conf).

$ErrorActionPreference = "Stop"
$Xampp = if ($env:XAMPP_HOME) { $env:XAMPP_HOME } else { "C:\xampp" }
$Port = if ($env:API_PORT) { $env:API_PORT } else { "8080" }
$Root = Split-Path -Parent $PSScriptRoot
$Api = Join-Path $Root "api"
$Dir = Join-Path $Api "runtime\apache"
$Conf = Join-Path $Dir "httpd.conf"
$PidFile = Join-Path $Dir "httpd.pid"
$Httpd = Join-Path $Xampp "apache\bin\httpd.exe"
$PhpDir = Join-Path $Xampp "php"

function Fwd([string]$p) { $p -replace "\\", "/" }

function Write-Config {
    if (-not (Test-Path $Httpd)) { throw "Apache not found at $Httpd - install XAMPP or set XAMPP_HOME." }
    if (-not (Test-Path (Join-Path $PhpDir "php8apache2_4.dll"))) { throw "mod_php (php8apache2_4.dll) not found in $PhpDir." }
    New-Item -ItemType Directory -Force $Dir | Out-Null

    # php.ini: XAMPP's, plus OPcache. Later keys win, so the appended block overrides.
    $ini = Get-Content (Join-Path $PhpDir "php.ini") -Raw
    $ini += @"

; ---- added by scripts\api_server.ps1 (not in XAMPP's php.ini) ----
[opcache]
zend_extension=opcache
opcache.enable=1
opcache.memory_consumption=128
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
; Source edits are picked up within 2 s - this is a development server.
opcache.validate_timestamps=1
opcache.revalidate_freq=2
realpath_cache_size=4096K
realpath_cache_ttl=600
"@
    Set-Content -Path (Join-Path $Dir "php.ini") -Value $ini -Encoding ascii

    $web = Fwd (Join-Path $Api "web")
    $text = @"
# Generated by scripts\api_server.ps1 - edit the script, not this file.
ServerRoot "$(Fwd (Join-Path $Xampp 'apache'))"
Listen 127.0.0.1:$Port
ServerName 127.0.0.1:$Port
PidFile "$(Fwd $PidFile)"
ErrorLog "$(Fwd (Join-Path $Dir 'error.log'))"
LogLevel warn

LoadModule authz_core_module modules/mod_authz_core.so
LoadModule dir_module modules/mod_dir.so
LoadModule mime_module modules/mod_mime.so
LoadModule setenvif_module modules/mod_setenvif.so
LoadModule env_module modules/mod_env.so

LoadFile "$(Fwd (Join-Path $PhpDir 'php8ts.dll'))"
LoadFile "$(Fwd (Join-Path $PhpDir 'libpq.dll'))"
LoadModule php_module "$(Fwd (Join-Path $PhpDir 'php8apache2_4.dll'))"
PHPIniDir "$(Fwd $Dir)"

TypesConfig conf/mime.types
# Each thread keeps one persistent PostgreSQL connection (max_connections is 100).
ThreadsPerChild 24
MaxConnectionsPerChild 0
KeepAlive On
KeepAliveTimeout 5
ServerTokens Prod
ServerSignature Off

<Directory />
    AllowOverride None
    Require all denied
</Directory>

<VirtualHost 127.0.0.1:$Port>
    ServerName api.coalshield.localhost
    DocumentRoot "$web"
    # The bearer token must reach PHP.
    SetEnvIf Authorization "(.+)" HTTP_AUTHORIZATION=`$1
    <Directory "$web">
        Options -Indexes
        Require all granted
        DirectoryIndex index.php
        # Every path that is not a file goes to Yii (the same rule as serve.bat's router).
        FallbackResource /index.php
    </Directory>
    <FilesMatch "\.php$">
        SetHandler application/x-httpd-php
    </FilesMatch>
</VirtualHost>
"@
    Set-Content -Path $Conf -Value $text -Encoding ascii
    $env:PATH = "$PhpDir;$env:PATH"   # extension DLLs (libssl, icu, ...) live next to php.exe
    # httpd -t reports on stderr even when the syntax is fine; cmd keeps that from being an error.
    $test = cmd /c "`"$Httpd`" -t -f `"$Conf`" 2>&1"
    if ($LASTEXITCODE -ne 0) { throw "Apache configuration test failed: $test" }
}

function Get-ApachePid {
    if (-not (Test-Path $PidFile)) { return $null }
    $apachePid = [int](Get-Content $PidFile -Raw).Trim()
    if (Get-Process -Id $apachePid -ErrorAction SilentlyContinue) { return $apachePid }
    return $null
}

function Test-Listening {
    [bool](Get-NetTCPConnection -State Listen -LocalPort $Port -ErrorAction SilentlyContinue)
}

function Stop-Api {
    $apachePid = Get-ApachePid
    if ($apachePid) {
        & taskkill /PID $apachePid /T /F | Out-Null
        Remove-Item $PidFile -ErrorAction SilentlyContinue
        Write-Output "[ok] API (Apache) stopped."
    } else {
        Write-Output "[ok] API (Apache) was not running."
    }
}

switch ($Action.ToLower()) {
    "config" { Write-Config; Write-Output "[ok] Wrote $Conf" }
    "status" {
        $apachePid = Get-ApachePid
        if ($apachePid) { Write-Output "[ok] API (Apache) running, pid $apachePid, http://127.0.0.1:$Port/v1/health" }
        else { Write-Output "[--] API (Apache) not running."; exit 1 }
    }
    "stop" { Stop-Api }
    { $_ -in "start", "restart" } {
        if ($Action -eq "restart") { Stop-Api }
        if (Get-ApachePid) { Write-Output "[ok] API (Apache) is already running on port $Port."; exit 0 }
        if (Test-Listening) { Write-Output "[X] Port $Port is in use by another program (an old serve.bat window?)."; exit 1 }
        Write-Config
        Start-Process -FilePath $Httpd -ArgumentList @("-f", "`"$Conf`"") -WorkingDirectory $Dir -WindowStyle Hidden
        for ($i = 0; $i -lt 40; $i++) {
            Start-Sleep -Milliseconds 250
            if ((Get-ApachePid) -and (Test-Listening)) {
                Write-Output "[ok] API (Apache + mod_php, OPcache) on http://127.0.0.1:$Port/v1/health"
                exit 0
            }
        }
        Write-Output "[X] Apache did not start - see $(Join-Path $Dir 'error.log')"
        exit 1
    }
    default { Write-Output "Usage: scripts\api_server.bat start | stop | restart | status | config"; exit 2 }
}
