<?php

declare(strict_types=1);

namespace app\commands;

use Yii;
use yii\console\Controller;
use yii\console\ExitCode;

/**
 * docs/API.md, generated from what the API actually serves (Phase 8), so the list cannot drift:
 * every route of config/routes.php, the action behind it, whether it needs a token, and the
 * permission(s) the action checks.
 *
 *   yii docs/api            write docs/API.md
 *   yii docs/api --check    exit 1 if docs/API.md is not current (ApiDocTest runs this)
 */
class DocsController extends Controller
{
    public const DOC = '/../docs/API.md';
    public bool $check = false;

    public function options($actionID): array
    {
        return array_merge(parent::options($actionID), ['check']);
    }

    public function actionApi(): int
    {
        $text = self::renderDoc();
        $path = Yii::getAlias('@app') . self::DOC;
        if ($this->check) {
            $current = is_file($path) ? str_replace("\r\n", "\n", (string) file_get_contents($path)) : '';
            if ($current !== $text) {
                $this->stderr("docs/API.md is out of date: run  php yii docs/api\n");
                return ExitCode::DATAERR;
            }
            $this->stdout("docs/API.md is current.\n");
            return ExitCode::OK;
        }
        file_put_contents($path, $text);
        $this->stdout("docs/API.md written.\n");
        return ExitCode::OK;
    }

    /** @return list<array{method: string, path: string, route: string, auth: string, permissions: string}> */
    public static function routes(): array
    {
        $rows = [];
        foreach (require Yii::getAlias('@app') . '/config/routes.php' as $pattern => $route) {
            [$method, $path] = explode(' ', $pattern, 2);
            if ($method === 'OPTIONS') {
                continue;
            }
            [, $controllerId, $actionId] = explode('/', $route);
            $class = 'app\\modules\\v1\\controllers\\' . str_replace(' ', '', ucwords(str_replace('-', ' ', $controllerId))) . 'Controller';
            $method_ = 'action' . str_replace(' ', '', ucwords(str_replace('-', ' ', $actionId)));
            $permissions = [];
            $public = false;
            if (class_exists($class) && method_exists($class, $method_)) {
                $reflection = new \ReflectionMethod($class, $method_);
                $lines = file($reflection->getFileName());
                $body = implode('', array_slice($lines, $reflection->getStartLine() - 1, $reflection->getEndLine() - $reflection->getStartLine() + 1));
                preg_match_all("/(?:requirePermission|->can)\\('([a-zA-Z.]+)'/", $body, $m);
                $permissions = array_map(fn($p) => "`$p`", array_values(array_unique($m[1])));
                preg_match_all('/AccessRule::(assert\w+)/', $body, $m);
                foreach (array_unique($m[1]) as $rule) {
                    $permissions[] = "rule `AccessRule::$rule`";
                }
                if (str_contains($body, '$this->part(')) {
                    $permissions[] = "each part's own check";
                }
                $defaults = (new \ReflectionClass($class))->getDefaultProperties();
                $public = in_array($actionId, $defaults['publicActions'] ?? [], true);
                $apiKey = !is_subclass_of($class, \app\components\ApiController::class);
            }
            $display = preg_replace('/<([a-z_]+):[^>]+>/', '{$1}', $path);
            $rows[] = ['method' => $method, 'path' => '/' . $display, 'route' => "$controllerId/$actionId",
                'auth' => $public ? 'public' : (($apiKey ?? false) ? 'API key' : 'token'),
                'permissions' => $permissions ? implode(', ', $permissions) : ($public ? '-' : (($apiKey ?? false) ? 'the simulator key' : 'any signed-in account'))];
        }
        return $rows;
    }

    public static function renderDoc(): string
    {
        $rows = self::routes();
        $out = "# API endpoints\n\n";
        $out .= "Generated by `php yii docs/api` from `api/config/routes.php` and the actions' permission checks -\n";
        $out .= "do not edit by hand (`ApiDocTest` fails when this page is stale). Shapes, rules and examples:\n";
        $out .= "[api-contract.md](api-contract.md); who may do what: [access-control.md](access-control.md); changes\n";
        $out .= "from the prototype and per phase: [API_CHANGES.md](API_CHANGES.md).\n\n";
        $out .= "All paths are under `http://127.0.0.1:8080`. **token**: `Authorization: Bearer <JWT>` from\n";
        $out .= "`POST /v1/auth/login`; out-of-scope records answer 404, a missing permission 403. **public**: no token\n";
        $out .= "(rate-limited where it matters). **API key**: `X-Api-Key` (the sensor simulator).\n\n";
        $out .= sprintf("%d endpoints.\n\n", count($rows));
        $out .= "| Method | Path | Auth | Permission checked | Action |\n|---|---|---|---|---|\n";
        foreach ($rows as $r) {
            $out .= sprintf("| %s | `%s` | %s | %s | `%s` |\n", $r['method'], $r['path'], $r['auth'],
                $r['permissions'], $r['route']);
        }
        return $out;
    }
}
